version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudwatchtoslack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f74rv1tnq9z7"
s3_prefix = "cloudwatchtoslack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
